// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

#include "Item.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace game {
namespace item {
PROTOBUF_CONSTEXPR C_Item_Use::C_Item_Use(
    ::_pbi::ConstantInitialized){}
struct C_Item_UseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_Item_UseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_Item_UseDefaultTypeInternal() {}
  union {
    C_Item_Use _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_Item_UseDefaultTypeInternal _C_Item_Use_default_instance_;
PROTOBUF_CONSTEXPR C_Item_PickedUp::C_Item_PickedUp(
    ::_pbi::ConstantInitialized){}
struct C_Item_PickedUpDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_Item_PickedUpDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_Item_PickedUpDefaultTypeInternal() {}
  union {
    C_Item_PickedUp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_Item_PickedUpDefaultTypeInternal _C_Item_PickedUp_default_instance_;
}  // namespace item
}  // namespace game
static ::_pb::Metadata file_level_metadata_Item_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Item_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Item_2eproto = nullptr;

const uint32_t TableStruct_Item_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::item::C_Item_Use, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::item::C_Item_PickedUp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::game::item::C_Item_Use)},
  { 6, -1, -1, sizeof(::game::item::C_Item_PickedUp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::game::item::_C_Item_Use_default_instance_._instance,
  &::game::item::_C_Item_PickedUp_default_instance_._instance,
};

const char descriptor_table_protodef_Item_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nItem.proto\022\tgame.item\"\014\n\nC_Item_Use\"\021\n"
  "\017C_Item_PickedUpb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Item_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Item_2eproto = {
    false, false, 64, descriptor_table_protodef_Item_2eproto,
    "Item.proto",
    &descriptor_table_Item_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_Item_2eproto::offsets,
    file_level_metadata_Item_2eproto, file_level_enum_descriptors_Item_2eproto,
    file_level_service_descriptors_Item_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Item_2eproto_getter() {
  return &descriptor_table_Item_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Item_2eproto(&descriptor_table_Item_2eproto);
namespace game {
namespace item {

// ===================================================================

class C_Item_Use::_Internal {
 public:
};

C_Item_Use::C_Item_Use(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:game.item.C_Item_Use)
}
C_Item_Use::C_Item_Use(const C_Item_Use& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:game.item.C_Item_Use)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_Item_Use::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_Item_Use::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_Item_Use::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Item_2eproto_getter, &descriptor_table_Item_2eproto_once,
      file_level_metadata_Item_2eproto[0]);
}

// ===================================================================

class C_Item_PickedUp::_Internal {
 public:
};

C_Item_PickedUp::C_Item_PickedUp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:game.item.C_Item_PickedUp)
}
C_Item_PickedUp::C_Item_PickedUp(const C_Item_PickedUp& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:game.item.C_Item_PickedUp)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_Item_PickedUp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_Item_PickedUp::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_Item_PickedUp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Item_2eproto_getter, &descriptor_table_Item_2eproto_once,
      file_level_metadata_Item_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace item
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game::item::C_Item_Use*
Arena::CreateMaybeMessage< ::game::item::C_Item_Use >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::item::C_Item_Use >(arena);
}
template<> PROTOBUF_NOINLINE ::game::item::C_Item_PickedUp*
Arena::CreateMaybeMessage< ::game::item::C_Item_PickedUp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::item::C_Item_PickedUp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
