name: Coverage Checker

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: check_coverage
      uses: 5monkeys/cobertura-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        path: ./test_coverage/cobertura.xml
        minimum_coverage: 75
