# you should see this 
# https://github.com/marketplace/actions/cobertura-report
name: Coverage Checker

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: check_coverage
      uses: 5monkeys/cobertura-action@master
      with:
        skip_covered: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        path: ./test_coverage/cobertura.xml
        minimum_coverage: 75
